name: Lokalise Pull Translations
description: 'Checks for translations by tag and pulls them into the PR'
inputs:
  api-token:
    description: API token
    required: true
  ref:
    description: branch reference
    required: true
  requiredLangs:
    description: List of required iso languages separated by comma
    required: true
  filename:
    description: The Lokalise filename to use on new keys
    required: true
  directory:
    description: The directory to find language files
    required: true
  format:
    description: The file format to parse. (json, properties)
    required: true
  platform:
    description: The Lokalise platform to sync
    required: true
  project-id:
    description: The project ID
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
